{
 "title": "API Metrics",
 "tags": [ "prometheus" ],
 "panels": [
  {
   "title": "API Request Metrics",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "select_band_stats_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API CPU Metrics",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{host}} CPU usage" }
   ]
  },
  {
   "title": "API Memory Metrics",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", id=~\".*Eden Space.*\"}",
     "legendFormat": "{{host}} Memory usage"
    }
   ]
  }
 ]
}