{
 "title": "Database Metrics",
 "tags": [ "prometheus" ],
 "panels": [
  {
   "title": "Connections by status",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "active_connections_active", "legendFormat": "{{datname}} active connections" },
    { "expr": "active_connections_idle", "legendFormat": "{{datname}} idle connections" }
   ]
  },
  {
   "title": "Slow queries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "long_transactions_long_idle_transactions",
     "legendFormat": "long idle connections"
    }
   ]
  },
  {
   "title": "Blocked locks",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "postgres_locks_blocked_locks", "legendFormat": "blocked locks" }
   ]
  },
  {
   "title": "Select query performance",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "select_query_performance_avg_time",
     "legendFormat": "Average query time"
    },
    { "expr": "select_query_performance_calls", "legendFormat": "Calls num." }
   ]
  },
  {
   "title": "Insert query performance",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "insert_query_performance_avg_time",
     "legendFormat": "Average query time"
    },
    { "expr": "insert_query_performance_calls", "legendFormat": "Calls num." }
   ]
  },
  {
   "title": "N+1",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "nplus1_summary_suspicious_patterns_count",
     "legendFormat": "Number of suspicious N+1 patterns detected"
    },
    {
     "expr": "nplus1_summary_total_suspicious_calls",
     "legendFormat": "Total calls of suspicious patterns"
    },
    {
     "expr": "nplus1_summary_avg_pattern_time_ms",
     "legendFormat": "Average execution time of suspicious patterns (ms)"
    },
    {
     "expr": "nplus1_summary_total_suspicious_time_seconds",
     "legendFormat": "Total time spent on suspicious patterns (seconds)"
    },
    {
     "expr": "nplus1_summary_high_volume_patterns",
     "legendFormat": "Number of patterns with >1000 calls"
    },
    {
     "expr": "nplus1_summary_slow_patterns",
     "legendFormat": "Number of patterns with avg time >100ms"
    }
   ]
  }
 ]
}